### ISSUE TITLE
Blockchain.info API does not support native segwit addresses

### ISSUE THREAD

**Issue by mightyx** [UdoBretz/Bitcoin-MoneyMoney#1] opened 2020-07-26 12:51 UTC
Example:
https://blockchain.info/q/addressbalance/bc1q5shngj24323nsrmxv99st02na6srekfctt30ch?confirmations=6
This will respond: Invalid Bitcoin Address

But it is actually a valid Bitcoin Address with native segwit support:
https://www.blockchain.com/de/btc/address/bc1q5shngj24323nsrmxv99st02na6srekfctt30ch

Full error from moneymoney error log:
```
The server responded with the error message: Internal Server Error. Retrying...
Sending: GET https://blockchain.info/q/addressbalance/bc1q5shngj24323nsrmxv99st02na6srekfctt30ch?confirmations=6
HTTPS response: Internal Server Error
Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.
```

I guess the current blockchain API does not support native segwit address, so let's see if we can find a solution:
https://www.blockchain.com/api/q (this is what we use currently)
https://www.blockchain.com/api/blockchain_api (also does not work), Example: https://blockchain.info/rawaddr/bc1q5shngj24323nsrmxv99st02na6srekfctt30ch

It seems like the api from blockcypher works:
https://api.blockcypher.com/v1/btc/main/addrs/bc1q5shngj24323nsrmxv99st02na6srekfctt30ch

API Limits: https://www.blockcypher.com/dev/bitcoin/#rate-limits-and-tokens

**Comment by UdoBretz** [comment] 2020-08-24 12:51
Hello,

Thank you very much for your detailed problem description. 
The issue is now fixed in v.0.4 like you suggested. 

Best regards, 
Udo

**Closed as completed by UdoBretz** 2020-08-24 12:51 UTC
